---
- name: Install required packages on new servers
  hosts: all
  become: yes
  tasks:
    - name: Install packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - tmux
        - vim
        - git
        - nodejs

    - name: Copy tmux.conf to user's home directory
      copy:
        src: tmux.conf
        dest: ~/.tmux.conf
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
